/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hanhan 's blog",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "原始类型",
      "frontmatter": {},
      "regularPath": "/blog/TypeScript/1-%E5%9F%BA%E7%A1%80.html",
      "relativePath": "blog/TypeScript/1-基础.md",
      "key": "v-2edf8c38",
      "path": "/blog/TypeScript/1-%E5%9F%BA%E7%A1%80.html",
      "headers": [
        {
          "level": 2,
          "title": "原始类型",
          "slug": "原始类型"
        },
        {
          "level": 3,
          "title": "布尔值",
          "slug": "布尔值"
        },
        {
          "level": 3,
          "title": "数值",
          "slug": "数值"
        },
        {
          "level": 3,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 3,
          "title": "空值",
          "slug": "空值"
        },
        {
          "level": 3,
          "title": "Null 和 Undefined",
          "slug": "null-和-undefined"
        },
        {
          "level": 2,
          "title": "任意值",
          "slug": "任意值"
        },
        {
          "level": 2,
          "title": "类型推论",
          "slug": "类型推论"
        },
        {
          "level": 2,
          "title": "联合类型",
          "slug": "联合类型"
        },
        {
          "level": 2,
          "title": "对象的类型——接口",
          "slug": "对象的类型-接口"
        },
        {
          "level": 3,
          "title": "可选属性",
          "slug": "可选属性"
        },
        {
          "level": 3,
          "title": "任意属性",
          "slug": "任意属性"
        },
        {
          "level": 3,
          "title": "只读属性",
          "slug": "只读属性"
        },
        {
          "level": 2,
          "title": "数组的类型",
          "slug": "数组的类型"
        },
        {
          "level": 3,
          "title": "「类型 + 方括号」表示法",
          "slug": "「类型-方括号」表示法"
        },
        {
          "level": 3,
          "title": "数组泛型",
          "slug": "数组泛型"
        },
        {
          "level": 3,
          "title": "用接口表示数组",
          "slug": "用接口表示数组"
        },
        {
          "level": 3,
          "title": "类数组",
          "slug": "类数组"
        },
        {
          "level": 3,
          "title": "用 any 表示数组中允许出现任意类型",
          "slug": "用-any-表示数组中允许出现任意类型"
        },
        {
          "level": 2,
          "title": "函数的类型",
          "slug": "函数的类型"
        },
        {
          "level": 3,
          "title": "函数声明",
          "slug": "函数声明"
        },
        {
          "level": 3,
          "title": "函数表达式",
          "slug": "函数表达式"
        },
        {
          "level": 3,
          "title": "完整的函数类型",
          "slug": "完整的函数类型"
        },
        {
          "level": 3,
          "title": "推断类型",
          "slug": "推断类型"
        },
        {
          "level": 3,
          "title": "接口定义函数的形状",
          "slug": "接口定义函数的形状"
        },
        {
          "level": 3,
          "title": "可选参数和默认参数",
          "slug": "可选参数和默认参数"
        },
        {
          "level": 3,
          "title": "剩余参数",
          "slug": "剩余参数"
        },
        {
          "level": 3,
          "title": "重载 overload",
          "slug": "重载-overload"
        },
        {
          "level": 2,
          "title": "类型断言",
          "slug": "类型断言"
        },
        {
          "level": 3,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 3,
          "title": "用途",
          "slug": "用途"
        },
        {
          "level": 3,
          "title": "限制",
          "slug": "限制"
        },
        {
          "level": 2,
          "title": "内置对象",
          "slug": "内置对象"
        },
        {
          "level": 2,
          "title": "声明文件",
          "slug": "声明文件"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/browser/",
      "relativePath": "blog/browser/index.md",
      "key": "v-25eca182",
      "path": "/blog/browser/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "我的主页",
        "tagline": "My homepage",
        "actionText": "技术文档 →",
        "actionLink": "/blog/",
        "footer": "Hanhan的个人博客"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-374e8902",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/browser/Jetbrains%E7%B3%BB%E5%88%97%E4%BA%A7%E5%93%81%E9%87%8D%E7%BD%AE%E8%AF%95%E7%94%A8%E6%96%B9%E6%B3%95.html",
      "relativePath": "blog/browser/Jetbrains系列产品重置试用方法.md",
      "key": "v-12d7d70c",
      "path": "/blog/browser/Jetbrains%E7%B3%BB%E5%88%97%E4%BA%A7%E5%93%81%E9%87%8D%E7%BD%AE%E8%AF%95%E7%94%A8%E6%96%B9%E6%B3%95.html"
    },
    {
      "title": "谷歌浏览器",
      "frontmatter": {},
      "regularPath": "/blog/browser/google%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E4%BD%8D%E7%BD%AE.html",
      "relativePath": "blog/browser/google扩展程序位置.md",
      "key": "v-7a329d3d",
      "path": "/blog/browser/google%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E4%BD%8D%E7%BD%AE.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/browser/%E6%90%9C%E7%B4%A2%E6%A1%86.html",
      "relativePath": "blog/browser/搜索框.md",
      "key": "v-3d69ad9a",
      "path": "/blog/browser/%E6%90%9C%E7%B4%A2%E6%A1%86.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/canvas/",
      "relativePath": "blog/canvas/index.md",
      "key": "v-56a60d15",
      "path": "/blog/canvas/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/browser/meta.html",
      "relativePath": "blog/browser/meta.md",
      "key": "v-566506b6",
      "path": "/blog/browser/meta.html"
    },
    {
      "title": "TypeScript",
      "frontmatter": {},
      "regularPath": "/blog/TypeScript/",
      "relativePath": "blog/TypeScript/index.md",
      "key": "v-74e42bf5",
      "path": "/blog/TypeScript/",
      "headers": [
        {
          "level": 2,
          "title": "类型系统",
          "slug": "类型系统"
        },
        {
          "level": 3,
          "title": "TypeScript 是静态类型",
          "slug": "typescript-是静态类型"
        },
        {
          "level": 3,
          "title": "TypeScript 是弱类型",
          "slug": "typescript-是弱类型"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/browser/%E6%B8%B2%E6%9F%93.html",
      "relativePath": "blog/browser/渲染.md",
      "key": "v-456f4304",
      "path": "/blog/browser/%E6%B8%B2%E6%9F%93.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/es6/",
      "relativePath": "blog/es6/index.md",
      "key": "v-4bbd3f02",
      "path": "/blog/es6/"
    },
    {
      "title": "css",
      "frontmatter": {},
      "regularPath": "/blog/css/",
      "relativePath": "blog/css/index.md",
      "key": "v-02b5c2ee",
      "path": "/blog/css/"
    },
    {
      "title": "前端常用静态文件服务器",
      "frontmatter": {},
      "regularPath": "/blog/browser/%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8.html",
      "relativePath": "blog/browser/静态文件服务器.md",
      "key": "v-264b91c4",
      "path": "/blog/browser/%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "运用anywhere",
          "slug": "运用anywhere"
        },
        {
          "level": 2,
          "title": "运用lite-server",
          "slug": "运用lite-server"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/jq/",
      "relativePath": "blog/jq/index.md",
      "key": "v-11b17db5",
      "path": "/blog/jq/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/canvas/%E7%B2%92%E5%AD%90%E7%89%B9%E6%95%88.html",
      "relativePath": "blog/canvas/粒子特效.md",
      "key": "v-0bb5c711",
      "path": "/blog/canvas/%E7%B2%92%E5%AD%90%E7%89%B9%E6%95%88.html"
    },
    {
      "title": "目录",
      "frontmatter": {
        "pageClass": "custom-page-class"
      },
      "regularPath": "/blog/",
      "relativePath": "blog/index.md",
      "key": "v-134abdf8",
      "path": "/blog/"
    },
    {
      "title": "jQuery 效果 - animate() 方法",
      "frontmatter": {},
      "regularPath": "/blog/jq/animate%E6%96%B9%E6%B3%95.html",
      "relativePath": "blog/jq/animate方法.md",
      "key": "v-1c3c6667",
      "path": "/blog/jq/animate%E6%96%B9%E6%B3%95.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/es6/ECMAScript%206%20%E5%85%A5%E9%97%A8---%E9%98%AE%E4%B8%80%E5%B3%B0.html",
      "relativePath": "blog/es6/ECMAScript 6 入门---阮一峰.md",
      "key": "v-00779823",
      "path": "/blog/es6/ECMAScript%206%20%E5%85%A5%E9%97%A8---%E9%98%AE%E4%B8%80%E5%B3%B0.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/js/",
      "relativePath": "blog/js/index.md",
      "key": "v-a5f37d16",
      "path": "/blog/js/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/node/glob.html",
      "relativePath": "blog/node/glob.md",
      "key": "v-7ca3a650",
      "path": "/blog/node/glob.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/browser/%E9%A1%B5%E9%9D%A2%E5%88%B7%E6%96%B0%E6%8F%90%E7%A4%BA.html",
      "relativePath": "blog/browser/页面刷新提示.md",
      "key": "v-a926ae3c",
      "path": "/blog/browser/%E9%A1%B5%E9%9D%A2%E5%88%B7%E6%96%B0%E6%8F%90%E7%A4%BA.html",
      "headers": [
        {
          "level": 2,
          "title": "建议使用 window.onXXXEvent 绑定方法，因为该方法在 Chrome 和 Firefox 中无论是刷新还是关闭都会弹窗；而 window.addEventListener 这种绑定方式在关闭选项卡的时候是不提示的！",
          "slug": "建议使用-window-onxxxevent-绑定方法-因为该方法在-chrome-和-firefox-中无论是刷新还是关闭都会弹窗-而-window-addeventlistener-这种绑定方式在关闭选项卡的时候是不提示的"
        }
      ]
    },
    {
      "title": "node",
      "frontmatter": {},
      "regularPath": "/blog/node/",
      "relativePath": "blog/node/index.md",
      "key": "v-3c8e2cd6",
      "path": "/blog/node/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/python/",
      "relativePath": "blog/python/index.md",
      "key": "v-213b7ad6",
      "path": "/blog/python/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/jq/jquery-note.html",
      "relativePath": "blog/jq/jquery-note.md",
      "key": "v-2e268d48",
      "path": "/blog/jq/jquery-note.html"
    },
    {
      "title": "cached",
      "frontmatter": {},
      "regularPath": "/blog/js/utils.html",
      "relativePath": "blog/js/utils.md",
      "key": "v-045dd09c",
      "path": "/blog/js/utils.html"
    },
    {
      "title": "concurrently",
      "frontmatter": {},
      "regularPath": "/blog/node/npm%E5%B8%B8%E7%94%A8%E6%A8%A1%E5%9D%97.html",
      "relativePath": "blog/node/npm常用模块.md",
      "key": "v-19109dea",
      "path": "/blog/node/npm%E5%B8%B8%E7%94%A8%E6%A8%A1%E5%9D%97.html",
      "headers": [
        {
          "level": 2,
          "title": "concurrently",
          "slug": "concurrently"
        },
        {
          "level": 2,
          "title": "cross-env",
          "slug": "cross-env"
        },
        {
          "level": 2,
          "title": "watch",
          "slug": "watch"
        },
        {
          "level": 2,
          "title": "fs-extra",
          "slug": "fs-extra"
        },
        {
          "level": 2,
          "title": "path",
          "slug": "path"
        },
        {
          "level": 2,
          "title": "glob",
          "slug": "glob"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/es6/promise.html",
      "relativePath": "blog/es6/promise.md",
      "key": "v-21c6b0b4",
      "path": "/blog/es6/promise.html"
    },
    {
      "title": "path",
      "frontmatter": {},
      "regularPath": "/blog/node/path.html",
      "relativePath": "blog/node/path.md",
      "key": "v-00a340fe",
      "path": "/blog/node/path.html"
    },
    {
      "title": "列表生成式",
      "frontmatter": {},
      "regularPath": "/blog/python/generator.html",
      "relativePath": "blog/python/generator.md",
      "key": "v-3f507708",
      "path": "/blog/python/generator.html",
      "headers": [
        {
          "level": 3,
          "title": "列表生成式",
          "slug": "列表生成式"
        },
        {
          "level": 2,
          "title": "生成器",
          "slug": "生成器"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/react/create-react-app.html",
      "relativePath": "blog/react/create-react-app.md",
      "key": "v-96737e14",
      "path": "/blog/react/create-react-app.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/python/python%E5%87%BD%E6%95%B0.html",
      "relativePath": "blog/python/python函数.md",
      "key": "v-25cac6e1",
      "path": "/blog/python/python%E5%87%BD%E6%95%B0.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/react/",
      "relativePath": "blog/react/index.md",
      "key": "v-15b3dede",
      "path": "/blog/react/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/python/python%E5%9F%BA%E7%A1%80.html",
      "relativePath": "blog/python/python基础.md",
      "key": "v-47eb9de6",
      "path": "/blog/python/python%E5%9F%BA%E7%A1%80.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/python/python%E7%B1%BB.html",
      "relativePath": "blog/python/python类.md",
      "key": "v-7a31fde2",
      "path": "/blog/python/python%E7%B1%BB.html"
    },
    {
      "title": "module",
      "frontmatter": {},
      "regularPath": "/blog/vue/vuex.html",
      "relativePath": "blog/vue/vuex.md",
      "key": "v-796b90d6",
      "path": "/blog/vue/vuex.html",
      "headers": [
        {
          "level": 3,
          "title": "module",
          "slug": "module"
        }
      ]
    },
    {
      "title": "从文件中读取数据",
      "frontmatter": {},
      "regularPath": "/blog/python/python%E6%96%87%E4%BB%B6.html",
      "relativePath": "blog/python/python文件.md",
      "key": "v-9fd04736",
      "path": "/blog/python/python%E6%96%87%E4%BB%B6.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/python/python%E5%BC%82%E5%B8%B8.html",
      "relativePath": "blog/python/python异常.md",
      "key": "v-45ce2dc7",
      "path": "/blog/python/python%E5%BC%82%E5%B8%B8.html"
    },
    {
      "title": "vue学习文档",
      "frontmatter": {},
      "regularPath": "/blog/vue/",
      "relativePath": "blog/vue/index.md",
      "key": "v-68f2d303",
      "path": "/blog/vue/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/vue/vue%E6%BA%90%E7%A0%81-7-%E5%93%8D%E5%BA%94%E5%BC%8F%E7%B3%BB%E7%BB%9F%E6%9E%84%E5%BB%BA.html",
      "relativePath": "blog/vue/vue源码-7-响应式系统构建.md",
      "key": "v-6f3e0c5e",
      "path": "/blog/vue/vue%E6%BA%90%E7%A0%81-7-%E5%93%8D%E5%BA%94%E5%BC%8F%E7%B3%BB%E7%BB%9F%E6%9E%84%E5%BB%BA.html"
    },
    {
      "title": "安装python",
      "frontmatter": {},
      "regularPath": "/blog/python/%E5%88%9D%E5%A7%8B.html",
      "relativePath": "blog/python/初始.md",
      "key": "v-35cd1ec5",
      "path": "/blog/python/%E5%88%9D%E5%A7%8B.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/vue/vue%E6%BA%90%E7%A0%81-4-%E5%AE%8C%E6%95%B4%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html",
      "relativePath": "blog/vue/vue源码-4-完整渲染流程.md",
      "key": "v-5a8e197a",
      "path": "/blog/vue/vue%E6%BA%90%E7%A0%81-4-%E5%AE%8C%E6%95%B4%E6%B8%B2%E6%9F%93%E6%B5%81%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "Virtual DOM",
          "slug": "virtual-dom"
        },
        {
          "level": 2,
          "title": "Vnode",
          "slug": "vnode"
        },
        {
          "level": 3,
          "title": "Vnode构造函数",
          "slug": "vnode构造函数"
        },
        {
          "level": 3,
          "title": "创建Vnode注释节点",
          "slug": "创建vnode注释节点"
        },
        {
          "level": 3,
          "title": "创建Vnode文本节点",
          "slug": "创建vnode文本节点"
        },
        {
          "level": 3,
          "title": "克隆vnode",
          "slug": "克隆vnode"
        },
        {
          "level": 2,
          "title": "Virtual DOM的创建",
          "slug": "virtual-dom的创建"
        },
        {
          "level": 2,
          "title": "虚拟Vnode映射成真实DOM",
          "slug": "虚拟vnode映射成真实dom"
        }
      ]
    },
    {
      "title": "丰富的选项合并策略",
      "frontmatter": {},
      "regularPath": "/blog/vue/vue%E6%BA%90%E7%A0%81-1-%E4%B8%B0%E5%AF%8C%E7%9A%84%E9%80%89%E9%A1%B9%E5%90%88%E5%B9%B6%E7%AD%96%E7%95%A5.html",
      "relativePath": "blog/vue/vue源码-1-丰富的选项合并策略.md",
      "key": "v-13da322f",
      "path": "/blog/vue/vue%E6%BA%90%E7%A0%81-1-%E4%B8%B0%E5%AF%8C%E7%9A%84%E9%80%89%E9%A1%B9%E5%90%88%E5%B9%B6%E7%AD%96%E7%95%A5.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue的引入",
          "slug": "vue的引入"
        },
        {
          "level": 3,
          "title": "基础使用",
          "slug": "基础使用"
        },
        {
          "level": 3,
          "title": "Vue构造器",
          "slug": "vue构造器"
        },
        {
          "level": 2,
          "title": "构造器的默认选项",
          "slug": "构造器的默认选项"
        },
        {
          "level": 2,
          "title": "选项检验",
          "slug": "选项检验"
        },
        {
          "level": 3,
          "title": "components规范检验",
          "slug": "components规范检验"
        },
        {
          "level": 3,
          "title": "props规范检验",
          "slug": "props规范检验"
        },
        {
          "level": 3,
          "title": "inject的规范校验",
          "slug": "inject的规范校验"
        },
        {
          "level": 3,
          "title": "directive的规范校验",
          "slug": "directive的规范校验"
        },
        {
          "level": 2,
          "title": "子类构造器",
          "slug": "子类构造器"
        },
        {
          "level": 2,
          "title": "合并策略",
          "slug": "合并策略"
        },
        {
          "level": 2,
          "title": "常规选项的合并",
          "slug": "常规选项的合并"
        },
        {
          "level": 3,
          "title": "el的合并",
          "slug": "el的合并"
        },
        {
          "level": 3,
          "title": "data合并",
          "slug": "data合并"
        },
        {
          "level": 2,
          "title": "自带资源选项合并",
          "slug": "自带资源选项合并"
        },
        {
          "level": 2,
          "title": "生命周期钩子函数的合并",
          "slug": "生命周期钩子函数的合并"
        },
        {
          "level": 2,
          "title": "watch选项合并",
          "slug": "watch选项合并"
        },
        {
          "level": 2,
          "title": "props methods inject computed合并",
          "slug": "props-methods-inject-computed合并"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/vue/%E6%8F%92%E6%A7%BD.html",
      "relativePath": "blog/vue/插槽.md",
      "key": "v-2dc02c40",
      "path": "/blog/vue/%E6%8F%92%E6%A7%BD.html"
    },
    {
      "title": "基础的数据代理检测",
      "frontmatter": {},
      "regularPath": "/blog/vue/vue%E6%BA%90%E7%A0%81-2-%E5%9F%BA%E7%A1%80%E7%9A%84%E6%95%B0%E6%8D%AE%E4%BB%A3%E7%90%86%E6%A3%80%E6%B5%8B.html",
      "relativePath": "blog/vue/vue源码-2-基础的数据代理检测.md",
      "key": "v-4b847742",
      "path": "/blog/vue/vue%E6%BA%90%E7%A0%81-2-%E5%9F%BA%E7%A1%80%E7%9A%84%E6%95%B0%E6%8D%AE%E4%BB%A3%E7%90%86%E6%A3%80%E6%B5%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "Object.defineProperty",
          "slug": "object-defineproperty"
        },
        {
          "level": 2,
          "title": "Proxy",
          "slug": "proxy"
        },
        {
          "level": 2,
          "title": "initProxy",
          "slug": "initproxy"
        },
        {
          "level": 3,
          "title": "handlers的实现",
          "slug": "handlers的实现"
        }
      ]
    },
    {
      "title": "组件基础",
      "frontmatter": {},
      "regularPath": "/blog/vue/%E7%BB%84%E4%BB%B6.html",
      "relativePath": "blog/vue/组件.md",
      "key": "v-114c0293",
      "path": "/blog/vue/%E7%BB%84%E4%BB%B6.html",
      "headers": [
        {
          "level": 3,
          "title": "组件基础",
          "slug": "组件基础"
        },
        {
          "level": 3,
          "title": "组件注册",
          "slug": "组件注册"
        },
        {
          "level": 3,
          "title": "模块系统",
          "slug": "模块系统"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/vue/%E8%BF%87%E6%BB%A4%E5%99%A8.html",
      "relativePath": "blog/vue/过滤器.md",
      "key": "v-b7563b26",
      "path": "/blog/vue/%E8%BF%87%E6%BB%A4%E5%99%A8.html"
    },
    {
      "title": "Vue 函数式组件 functional",
      "frontmatter": {},
      "regularPath": "/blog/vue/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6.html",
      "relativePath": "blog/vue/函数式组件.md",
      "key": "v-312bc899",
      "path": "/blog/vue/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6.html",
      "headers": [
        {
          "level": 3,
          "title": "Vue 函数式组件 functional",
          "slug": "vue-函数式组件-functional"
        }
      ]
    },
    {
      "title": "webpack",
      "frontmatter": {},
      "regularPath": "/blog/webpack/1-%E8%B5%B7%E6%AD%A5.html",
      "relativePath": "blog/webpack/1-起步.md",
      "key": "v-1a5be792",
      "path": "/blog/webpack/1-%E8%B5%B7%E6%AD%A5.html",
      "headers": [
        {
          "level": 2,
          "title": "webpack",
          "slug": "webpack"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "起步",
          "slug": "起步"
        },
        {
          "level": 3,
          "title": "管理资源",
          "slug": "管理资源"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/webpack/",
      "relativePath": "blog/webpack/index.md",
      "key": "v-706a6c96",
      "path": "/blog/webpack/"
    },
    {
      "title": "webpack baseConfig",
      "frontmatter": {},
      "regularPath": "/blog/webpack/baseConfig.html",
      "relativePath": "blog/webpack/baseConfig.md",
      "key": "v-28788596",
      "path": "/blog/webpack/baseConfig.html",
      "headers": [
        {
          "level": 2,
          "title": "发现项目逐渐变大之后，webpack打包会很慢，解决办法：",
          "slug": "发现项目逐渐变大之后-webpack打包会很慢-解决办法"
        },
        {
          "level": 2,
          "title": "webpackMerge",
          "slug": "webpackmerge"
        },
        {
          "level": 2,
          "title": "解析(resolve)",
          "slug": "解析-resolve"
        },
        {
          "level": 3,
          "title": "resolve.alias  使用别名/简化相对路径",
          "slug": "resolve-alias-使用别名-简化相对路径"
        },
        {
          "level": 3,
          "title": "resolve.extensions",
          "slug": "resolve-extensions"
        },
        {
          "level": 3,
          "title": "resolve.modules",
          "slug": "resolve-modules"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/webpack/2-%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5.html",
      "relativePath": "blog/webpack/2-核心概念.md",
      "key": "v-4e0e183c",
      "path": "/blog/webpack/2-%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5.html",
      "headers": [
        {
          "level": 2,
          "title": "入口起点entry",
          "slug": "入口起点entry"
        },
        {
          "level": 3,
          "title": "单个入口",
          "slug": "单个入口"
        },
        {
          "level": 3,
          "title": "对象语法",
          "slug": "对象语法"
        },
        {
          "level": 2,
          "title": "出口(output)",
          "slug": "出口-output"
        },
        {
          "level": 3,
          "title": "多个入口起点",
          "slug": "多个入口起点"
        },
        {
          "level": 3,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "loader",
          "slug": "loader"
        },
        {
          "level": 2,
          "title": "插件",
          "slug": "插件"
        }
      ]
    },
    {
      "title": "loader",
      "frontmatter": {},
      "regularPath": "/blog/webpack/loader.html",
      "relativePath": "blog/webpack/loader.md",
      "key": "v-f041bad4",
      "path": "/blog/webpack/loader.html",
      "headers": [
        {
          "level": 2,
          "title": "文件",
          "slug": "文件"
        },
        {
          "level": 3,
          "title": "raw-loader",
          "slug": "raw-loader"
        },
        {
          "level": 3,
          "title": "url-loader",
          "slug": "url-loader"
        },
        {
          "level": 3,
          "title": "file-loader",
          "slug": "file-loader"
        },
        {
          "level": 3,
          "title": "ref-loader",
          "slug": "ref-loader"
        },
        {
          "level": 2,
          "title": "转义",
          "slug": "转义"
        },
        {
          "level": 3,
          "title": "babel-loader",
          "slug": "babel-loader"
        }
      ]
    },
    {
      "title": "管理输出",
      "frontmatter": {},
      "regularPath": "/blog/webpack/3-%E7%AE%A1%E7%90%86%E8%BE%93%E5%87%BA.html",
      "relativePath": "blog/webpack/3-管理输出.md",
      "key": "v-b949e93e",
      "path": "/blog/webpack/3-%E7%AE%A1%E7%90%86%E8%BE%93%E5%87%BA.html",
      "headers": [
        {
          "level": 3,
          "title": "管理输出",
          "slug": "管理输出"
        },
        {
          "level": 3,
          "title": "output.chunkFilename",
          "slug": "output-chunkfilename"
        },
        {
          "level": 3,
          "title": "source maps",
          "slug": "source-maps"
        }
      ]
    },
    {
      "title": "组件两种注册方式",
      "frontmatter": {},
      "regularPath": "/blog/vue/vue%E6%BA%90%E7%A0%81-5-%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80.html",
      "relativePath": "blog/vue/vue源码-5-组件基础.md",
      "key": "v-9e8a8e3a",
      "path": "/blog/vue/vue%E6%BA%90%E7%A0%81-5-%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80.html",
      "headers": [
        {
          "level": 2,
          "title": "组件两种注册方式",
          "slug": "组件两种注册方式"
        },
        {
          "level": 3,
          "title": "全局注册",
          "slug": "全局注册"
        },
        {
          "level": 3,
          "title": "局部注册",
          "slug": "局部注册"
        },
        {
          "level": 3,
          "title": "注册过程",
          "slug": "注册过程"
        },
        {
          "level": 2,
          "title": "组件Vnode创建",
          "slug": "组件vnode创建"
        },
        {
          "level": 2,
          "title": "组件Vnode渲染真实DOM",
          "slug": "组件vnode渲染真实dom"
        },
        {
          "level": 2,
          "title": "建立组件联系",
          "slug": "建立组件联系"
        }
      ]
    },
    {
      "title": "npm script 使用",
      "frontmatter": {},
      "regularPath": "/blog/webpack/npm%20scripts%20%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.html",
      "relativePath": "blog/webpack/npm scripts 使用指南.md",
      "key": "v-452c062f",
      "path": "/blog/webpack/npm%20scripts%20%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.html",
      "headers": [
        {
          "level": 2,
          "title": "原理",
          "slug": "原理"
        },
        {
          "level": 2,
          "title": "传参",
          "slug": "传参"
        },
        {
          "level": 2,
          "title": "钩子",
          "slug": "钩子"
        }
      ]
    },
    {
      "title": "项目",
      "frontmatter": {},
      "regularPath": "/blog/webpack/dev-serverJS.html",
      "relativePath": "blog/webpack/dev-serverJS.md",
      "key": "v-4eb4ff76",
      "path": "/blog/webpack/dev-serverJS.html",
      "headers": [
        {
          "level": 2,
          "title": "vue-cli脚手架build目录中的dev-server.js配置文件",
          "slug": "vue-cli脚手架build目录中的dev-server-js配置文件"
        },
        {
          "level": 2,
          "title": "demo",
          "slug": "demo"
        }
      ]
    },
    {
      "title": "命令行接口",
      "frontmatter": {},
      "regularPath": "/blog/webpack/webpack-command%20line%20interface.html",
      "relativePath": "blog/webpack/webpack-command line interface.md",
      "key": "v-526cc9d4",
      "path": "/blog/webpack/webpack-command%20line%20interface.html",
      "headers": [
        {
          "level": 3,
          "title": "命令行接口",
          "slug": "命令行接口"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/webpack/vue-cli%E8%84%9A%E6%89%8B%E6%9E%B6build%E7%9B%AE%E5%BD%95%E4%B8%AD%E7%9A%84dev-server.js%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6.html",
      "relativePath": "blog/webpack/vue-cli脚手架build目录中的dev-server.js配置文件.md",
      "key": "v-a84461e0",
      "path": "/blog/webpack/vue-cli%E8%84%9A%E6%89%8B%E6%9E%B6build%E7%9B%AE%E5%BD%95%E4%B8%AD%E7%9A%84dev-server.js%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6.html",
      "headers": [
        {
          "level": 2,
          "title": "demo",
          "slug": "demo"
        }
      ]
    },
    {
      "title": "modules",
      "frontmatter": {},
      "regularPath": "/blog/webpack/webpack-modules.html",
      "relativePath": "blog/webpack/webpack-modules.md",
      "key": "v-c1b398dc",
      "path": "/blog/webpack/webpack-modules.html",
      "headers": [
        {
          "level": 3,
          "title": "modules",
          "slug": "modules"
        }
      ]
    },
    {
      "title": "Entry",
      "frontmatter": {},
      "regularPath": "/blog/webpack/webpack-%E9%85%8D%E7%BD%AE.html",
      "relativePath": "blog/webpack/webpack-配置.md",
      "key": "v-04546be6",
      "path": "/blog/webpack/webpack-%E9%85%8D%E7%BD%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "Entry",
          "slug": "entry"
        },
        {
          "level": 2,
          "title": "Output",
          "slug": "output"
        }
      ]
    },
    {
      "title": "模块热替换",
      "frontmatter": {},
      "regularPath": "/blog/webpack/%E6%A8%A1%E5%9D%97%E7%83%AD%E6%9B%B4%E6%96%B0.html",
      "relativePath": "blog/webpack/模块热更新.md",
      "key": "v-583a201f",
      "path": "/blog/webpack/%E6%A8%A1%E5%9D%97%E7%83%AD%E6%9B%B4%E6%96%B0.html",
      "headers": [
        {
          "level": 3,
          "title": "模块热替换",
          "slug": "模块热替换"
        }
      ]
    },
    {
      "title": "插件",
      "frontmatter": {},
      "regularPath": "/blog/webpack/%E6%8F%92%E4%BB%B6plugins.html",
      "relativePath": "blog/webpack/插件plugins.md",
      "key": "v-5951d7cb",
      "path": "/blog/webpack/%E6%8F%92%E4%BB%B6plugins.html",
      "headers": [
        {
          "level": 2,
          "title": "Webpack5常用的插件",
          "slug": "webpack5常用的插件"
        },
        {
          "level": 3,
          "title": "webpack内置模块",
          "slug": "webpack内置模块"
        },
        {
          "level": 3,
          "title": "webpack-merge",
          "slug": "webpack-merge"
        },
        {
          "level": 3,
          "title": "webpack-dev-server",
          "slug": "webpack-dev-server"
        },
        {
          "level": 3,
          "title": "mini-css-extract-plugin",
          "slug": "mini-css-extract-plugin"
        },
        {
          "level": 3,
          "title": "html-webpack-plugin",
          "slug": "html-webpack-plugin"
        },
        {
          "level": 3,
          "title": "TerserPlugin 和 CssMinimizerPlugin",
          "slug": "terserplugin-和-cssminimizerplugin"
        },
        {
          "level": 3,
          "title": "compression-webpack-plugin",
          "slug": "compression-webpack-plugin"
        },
        {
          "level": 3,
          "title": "webpack-bundle-analyzer",
          "slug": "webpack-bundle-analyzer"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/webpack/npm-concurrently.html",
      "relativePath": "blog/webpack/npm-concurrently.md",
      "key": "v-6cc3dc94",
      "path": "/blog/webpack/npm-concurrently.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B0%8F%E7%A8%8B%E5%BA%8Fwebview.html",
      "relativePath": "blog/小程序/小程序webview.md",
      "key": "v-613fa26e",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B0%8F%E7%A8%8B%E5%BA%8Fwebview.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%8E%9F%E7%90%86.html",
      "relativePath": "blog/小程序/小程序原理.md",
      "key": "v-19fc4cf4",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%8E%9F%E7%90%86.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/IntersectionObserver.html",
      "relativePath": "blog/小程序/IntersectionObserver.md",
      "key": "v-beb5149c",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/IntersectionObserver.html"
    },
    {
      "title": "笔记",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/",
      "relativePath": "blog/小程序/index.md",
      "key": "v-f63cf266",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8EH5%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "relativePath": "blog/小程序/微信小程序与H5的区别.md",
      "key": "v-5272fb19",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8EH5%E7%9A%84%E5%8C%BA%E5%88%AB.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/wxs%E5%8F%8A%E5%B7%A6%E6%BB%91%E5%88%A0%E9%99%A4.html",
      "relativePath": "blog/小程序/wxs及左滑删除.md",
      "key": "v-a48bc88c",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/wxs%E5%8F%8A%E5%B7%A6%E6%BB%91%E5%88%A0%E9%99%A4.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%20-%20%E4%BD%BF%E7%94%A8npm.html",
      "relativePath": "blog/小程序/微信小程序 - 使用npm.md",
      "key": "v-fe2a4a22",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%20-%20%E4%BD%BF%E7%94%A8npm.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B7%A6%E6%BB%91%E5%88%A0%E9%99%A42.html",
      "relativePath": "blog/小程序/左滑删除2.md",
      "key": "v-553976a4",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B7%A6%E6%BB%91%E5%88%A0%E9%99%A42.html"
    },
    {
      "title": "使用 source map",
      "frontmatter": {},
      "regularPath": "/blog/webpack/%E5%BC%80%E5%8F%91.html",
      "relativePath": "blog/webpack/开发.md",
      "key": "v-bc5d6a98",
      "path": "/blog/webpack/%E5%BC%80%E5%8F%91.html",
      "headers": [
        {
          "level": 3,
          "title": "使用 source map",
          "slug": "使用-source-map"
        }
      ]
    },
    {
      "title": "生命周期",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
      "relativePath": "blog/小程序/生命周期.md",
      "key": "v-f63c7ae8",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "onLoad()",
          "slug": "onload"
        },
        {
          "level": 2,
          "title": "onShow()",
          "slug": "onshow"
        },
        {
          "level": 2,
          "title": "onReady()",
          "slug": "onready"
        },
        {
          "level": 2,
          "title": "onHide()",
          "slug": "onhide"
        },
        {
          "level": 2,
          "title": "onUnload()",
          "slug": "onunload"
        }
      ]
    },
    {
      "title": "数据请求怎么封装",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E6%95%B0%E6%8D%AE%E8%AF%B7%E6%B1%82.html",
      "relativePath": "blog/小程序/数据请求.md",
      "key": "v-0d38855c",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E6%95%B0%E6%8D%AE%E8%AF%B7%E6%B1%82.html"
    },
    {
      "title": "小程序:chooseimage成功会执行onHide和onShow",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%B8%A9%E5%9D%91.html",
      "relativePath": "blog/小程序/小程序踩坑.md",
      "key": "v-34b4d806",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%B8%A9%E5%9D%91.html",
      "headers": [
        {
          "level": 2,
          "title": "小程序:chooseimage成功会执行onHide和onShow",
          "slug": "小程序-chooseimage成功会执行onhide和onshow"
        },
        {
          "level": 2,
          "title": "小程序实现图片放大预览功能",
          "slug": "小程序实现图片放大预览功能"
        },
        {
          "level": 2,
          "title": "toDateString()",
          "slug": "todatestring"
        },
        {
          "level": 2,
          "title": "上传文件",
          "slug": "上传文件"
        },
        {
          "level": 2,
          "title": "小程序返回上一页携带参数",
          "slug": "小程序返回上一页携带参数"
        },
        {
          "level": 2,
          "title": "小程序左滑删除：",
          "slug": "小程序左滑删除"
        },
        {
          "level": 2,
          "title": "保存base图片到本地相册",
          "slug": "保存base图片到本地相册"
        },
        {
          "level": 2,
          "title": "去除按钮默认样式",
          "slug": "去除按钮默认样式"
        }
      ]
    },
    {
      "title": "WxValidate - 表单验证",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/WxValidate%20-%20%E8%A1%A8%E5%8D%95%E9%AA%8C%E8%AF%81.html",
      "relativePath": "blog/小程序/WxValidate - 表单验证.md",
      "key": "v-d12a6cac",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/WxValidate%20-%20%E8%A1%A8%E5%8D%95%E9%AA%8C%E8%AF%81.html",
      "headers": [
        {
          "level": 2,
          "title": "WxValidate - 表单验证",
          "slug": "wxvalidate-表单验证"
        },
        {
          "level": 2,
          "title": "插件介绍",
          "slug": "插件介绍"
        },
        {
          "level": 2,
          "title": "参数说明",
          "slug": "参数说明"
        },
        {
          "level": 2,
          "title": "内置校验规则",
          "slug": "内置校验规则"
        },
        {
          "level": 2,
          "title": "常用实例方法",
          "slug": "常用实例方法"
        },
        {
          "level": 2,
          "title": "addMethod(name, method, message) - 添加自定义校验",
          "slug": "addmethod-name-method-message-添加自定义校验"
        },
        {
          "level": 2,
          "title": "使用说明",
          "slug": "使用说明"
        }
      ]
    },
    {
      "title": "自定义组件",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6.html",
      "relativePath": "blog/小程序/自定义组件.md",
      "key": "v-58a5563a",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6.html",
      "headers": [
        {
          "level": 2,
          "title": "如何创建？？",
          "slug": "如何创建"
        },
        {
          "level": 2,
          "title": "如何使用？？",
          "slug": "如何使用"
        },
        {
          "level": 2,
          "title": "组件 wxml 的 slot",
          "slug": "组件-wxml-的-slot"
        },
        {
          "level": 2,
          "title": "虚拟化组件节点",
          "slug": "虚拟化组件节点"
        },
        {
          "level": 2,
          "title": "定义和使用 behaviors",
          "slug": "定义和使用-behaviors"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E7%BB%84%E4%BB%B6%E9%97%B4%E5%85%B3%E7%B3%BB.html",
      "relativePath": "blog/小程序/组件间关系.md",
      "key": "v-fef4848e",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E7%BB%84%E4%BB%B6%E9%97%B4%E5%85%B3%E7%B3%BB.html"
    },
    {
      "title": "微信小程序的相关文件类型",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E7%9B%B8%E5%85%B3%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "blog/小程序/相关文件类型.md",
      "key": "v-15ffd44c",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E7%9B%B8%E5%85%B3%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "JSON 配置",
          "slug": "json-配置"
        },
        {
          "level": 3,
          "title": "小程序配置 app.json",
          "slug": "小程序配置-app-json"
        },
        {
          "level": 3,
          "title": "工具配置 project.config.json",
          "slug": "工具配置-project-config-json"
        },
        {
          "level": 3,
          "title": "页面配置 page.json",
          "slug": "页面配置-page-json"
        }
      ]
    },
    {
      "title": "16th 设计模式-状态模式",
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/16th%20%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/16th 状态模式.md",
      "key": "v-84c82bc0",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/16th%20%E7%8A%B6%E6%80%81%E6%A8%A1%E5%BC%8F.html"
    },
    {
      "title": "wx.navigateTo(Object object)",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E6%96%B0%E5%A2%9E%E9%A1%B5%E9%9D%A2%E9%97%B4%E9%80%9A%E4%BF%A1%E6%8E%A5%E5%8F%A3.html",
      "relativePath": "blog/小程序/新增页面间通信接口.md",
      "key": "v-0dfb77b4",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E6%96%B0%E5%A2%9E%E9%A1%B5%E9%9D%A2%E9%97%B4%E9%80%9A%E4%BF%A1%E6%8E%A5%E5%8F%A3.html"
    },
    {
      "title": "页面事件处理函数",
      "frontmatter": {},
      "regularPath": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0.html",
      "relativePath": "blog/小程序/页面事件处理函数.md",
      "key": "v-3d272ec3",
      "path": "/blog/%E5%B0%8F%E7%A8%8B%E5%BA%8F/%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "页面事件处理函数",
          "slug": "页面事件处理函数"
        },
        {
          "level": 2,
          "title": "页面间通信",
          "slug": "页面间通信"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/",
      "relativePath": "book-study/JavaScript设计模式与开发实践/index.md",
      "key": "v-7bd75347",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/3th%E9%97%AD%E5%8C%85%E5%92%8C%E9%AB%98%E9%98%B6%E5%87%BD%E6%95%B0.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/3th闭包和高阶函数.md",
      "key": "v-4a26c068",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/3th%E9%97%AD%E5%8C%85%E5%92%8C%E9%AB%98%E9%98%B6%E5%87%BD%E6%95%B0.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/20th%E5%BC%80%E6%94%BE-%E5%B0%81%E9%97%AD%E5%8E%9F%E5%88%99.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/20th开放-封闭原则.md",
      "key": "v-4069a088",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/20th%E5%BC%80%E6%94%BE-%E5%B0%81%E9%97%AD%E5%8E%9F%E5%88%99.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/2th.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/2th.md",
      "key": "v-d7ab4434",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/2th.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/contents.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/contents.md",
      "key": "v-26fe1970",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/contents.html"
    },
    {
      "title": "代理模式",
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F%20%E5%91%BD%E4%BB%A4%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/代理模式 命令模式.md",
      "key": "v-31c161fb",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F%20%E5%91%BD%E4%BB%A4%E6%A8%A1%E5%BC%8F.html",
      "headers": [
        {
          "level": 3,
          "title": "代理模式",
          "slug": "代理模式"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/1th.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/1th.md",
      "key": "v-399bab30",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/1th.html"
    },
    {
      "title": "单例模式",
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F%20%E7%AD%96%E7%95%A5%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/单例模式 策略模式.md",
      "key": "v-1c34a264",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F%20%E7%AD%96%E7%95%A5%E6%A8%A1%E5%BC%8F.html",
      "headers": [
        {
          "level": 3,
          "title": "单例模式",
          "slug": "单例模式"
        },
        {
          "level": 3,
          "title": "策略模式",
          "slug": "策略模式"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84JavaScript/",
      "relativePath": "book-study/你不知道的JavaScript/index.md",
      "key": "v-7115f440",
      "path": "/book-study/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84JavaScript/"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E7%BB%84%E5%90%88%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/组合模式.md",
      "key": "v-4491b9fc",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E7%BB%84%E5%90%88%E6%A8%A1%E5%BC%8F.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E8%81%8C%E8%B4%A3%E9%93%BE%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/职责链模式.md",
      "key": "v-31c17396",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E8%81%8C%E8%B4%A3%E9%93%BE%E6%A8%A1%E5%BC%8F.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/22th%E4%BB%A3%E7%A0%81%E9%87%8D%E6%9E%84.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/22th代码重构.md",
      "key": "v-76c9cabc",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/22th%E4%BB%A3%E7%A0%81%E9%87%8D%E6%9E%84.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E5%9B%BE%E8%A7%A3http/2th.html",
      "relativePath": "book-study/图解http/2th.md",
      "key": "v-19de4b9c",
      "path": "/book-study/%E5%9B%BE%E8%A7%A3http/2th.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84JavaScript/%E8%A1%8C%E4%B8%BA%E5%A7%94%E6%89%98.html",
      "relativePath": "book-study/你不知道的JavaScript/行为委托.md",
      "key": "v-ce1010fe",
      "path": "/book-study/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84JavaScript/%E8%A1%8C%E4%B8%BA%E5%A7%94%E6%89%98.html"
    },
    {
      "title": "读书笔记",
      "frontmatter": {},
      "regularPath": "/book-study/",
      "relativePath": "book-study/index.md",
      "key": "v-b5617e84",
      "path": "/book-study/"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84JavaScript/%E4%B8%AD%E5%8D%B7-%E7%AC%AC%E4%BA%94%E7%AB%A0-%E8%AF%AD%E6%B3%95.html",
      "relativePath": "book-study/你不知道的JavaScript/中卷-第五章-语法.md",
      "key": "v-83acbde2",
      "path": "/book-study/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84JavaScript/%E4%B8%AD%E5%8D%B7-%E7%AC%AC%E4%BA%94%E7%AB%A0-%E8%AF%AD%E6%B3%95.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E5%9B%BE%E8%A7%A3http/",
      "relativePath": "book-study/图解http/index.md",
      "key": "v-4e9550d6",
      "path": "/book-study/%E5%9B%BE%E8%A7%A3http/"
    },
    {
      "title": "事件",
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/13th.html",
      "relativePath": "book-study/红宝书/13th.md",
      "key": "v-4e0f82ca",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/13th.html",
      "headers": [
        {
          "level": 3,
          "title": "事件",
          "slug": "事件"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/10th.html",
      "relativePath": "book-study/红宝书/10th.md",
      "key": "v-cb22072c",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/10th.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/20th-json.html",
      "relativePath": "book-study/红宝书/20th-json.md",
      "key": "v-771c4fb8",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/20th-json.html"
    },
    {
      "title": "离线应用",
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/23th.html",
      "relativePath": "book-study/红宝书/23th.md",
      "key": "v-38eb76ac",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/23th.html",
      "headers": [
        {
          "level": 3,
          "title": "离线应用",
          "slug": "离线应用"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/24th.html",
      "relativePath": "book-study/红宝书/24th.md",
      "key": "v-74bfc6ca",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/24th.html"
    },
    {
      "title": "js中使用函数的高级方法",
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/22th.html",
      "relativePath": "book-study/红宝书/22th.md",
      "key": "v-5254c28a",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/22th.html",
      "headers": [
        {
          "level": 3,
          "title": "js中使用函数的高级方法",
          "slug": "js中使用函数的高级方法"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/",
      "relativePath": "book-study/红宝书/index.md",
      "key": "v-0bf7c37f",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/"
    },
    {
      "title": "第一章 了解web和网络基础",
      "frontmatter": {},
      "regularPath": "/book-study/%E5%9B%BE%E8%A7%A3http/1th.html",
      "relativePath": "book-study/图解http/1th.md",
      "key": "v-9b18f688",
      "path": "/book-study/%E5%9B%BE%E8%A7%A3http/1th.html",
      "headers": [
        {
          "level": 2,
          "title": "网络基础TCP/IP",
          "slug": "网络基础tcp-ip"
        },
        {
          "level": 3,
          "title": "分层管理",
          "slug": "分层管理"
        },
        {
          "level": 3,
          "title": "TCP/IP通信传输流",
          "slug": "tcp-ip通信传输流"
        }
      ]
    },
    {
      "title": "新兴api",
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/25th.html",
      "relativePath": "book-study/红宝书/25th.md",
      "key": "v-05f548ea",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/25th.html",
      "headers": [
        {
          "level": 3,
          "title": "新兴api",
          "slug": "新兴api"
        },
        {
          "level": 3,
          "title": "File API",
          "slug": "file-api"
        },
        {
          "level": 3,
          "title": "读取拖放的文件",
          "slug": "读取拖放的文件"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/8th.html",
      "relativePath": "book-study/红宝书/8th.md",
      "key": "v-0198bb5c",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/8th.html"
    },
    {
      "title": "垃圾收集",
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/4th.html",
      "relativePath": "book-study/红宝书/4th.md",
      "key": "v-117e174c",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/4th.html",
      "headers": [
        {
          "level": 3,
          "title": "垃圾收集",
          "slug": "垃圾收集"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/strictMode.html",
      "relativePath": "book-study/红宝书/strictMode.md",
      "key": "v-3af341ec",
      "path": "/book-study/%E7%BA%A2%E5%AE%9D%E4%B9%A6/strictMode.html"
    },
    {
      "title": "订阅发布模式",
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E8%AE%A2%E9%98%85%E5%8F%91%E5%B8%83%E6%A8%A1%E5%BC%8F%20%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/订阅发布模式 迭代器模式.md",
      "key": "v-1b33aac4",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E8%AE%A2%E9%98%85%E5%8F%91%E5%B8%83%E6%A8%A1%E5%BC%8F%20%E8%BF%AD%E4%BB%A3%E5%99%A8%E6%A8%A1%E5%BC%8F.html",
      "headers": [
        {
          "level": 3,
          "title": "订阅发布模式",
          "slug": "订阅发布模式"
        },
        {
          "level": 3,
          "title": "迭代器模式",
          "slug": "迭代器模式"
        }
      ]
    },
    {
      "title": "模板方法模式",
      "frontmatter": {},
      "regularPath": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E6%A8%A1%E6%9D%BF%E6%96%B9%E6%B3%95%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "book-study/JavaScript设计模式与开发实践/模板方法模式.md",
      "key": "v-ba355f68",
      "path": "/book-study/JavaScript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%BC%80%E5%8F%91%E5%AE%9E%E8%B7%B5/%E6%A8%A1%E6%9D%BF%E6%96%B9%E6%B3%95%E6%A8%A1%E5%BC%8F.html"
    },
    {
      "title": "实例挂载流程和模板编译",
      "frontmatter": {},
      "regularPath": "/blog/vue/vue%E6%BA%90%E7%A0%81-3-%E5%AE%9E%E4%BE%8B%E6%8C%82%E8%BD%BD%E6%B5%81%E7%A8%8B%E5%92%8C%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html",
      "relativePath": "blog/vue/vue源码-3-实例挂载流程和模板编译.md",
      "key": "v-3a2c1019",
      "path": "/blog/vue/vue%E6%BA%90%E7%A0%81-3-%E5%AE%9E%E4%BE%8B%E6%8C%82%E8%BD%BD%E6%B5%81%E7%A8%8B%E5%92%8C%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91.html",
      "headers": [
        {
          "level": 2,
          "title": "实例的挂载渲染流程",
          "slug": "实例的挂载渲染流程"
        },
        {
          "level": 3,
          "title": "Runtime + Compiler",
          "slug": "runtime-compiler"
        },
        {
          "level": 3,
          "title": "Runtime Only",
          "slug": "runtime-only"
        },
        {
          "level": 3,
          "title": "实力挂载基本思路",
          "slug": "实力挂载基本思路"
        },
        {
          "level": 2,
          "title": "模板编译",
          "slug": "模板编译"
        },
        {
          "level": 3,
          "title": "template的三种写法",
          "slug": "template的三种写法"
        },
        {
          "level": 3,
          "title": "编译流程图解",
          "slug": "编译流程图解"
        },
        {
          "level": 3,
          "title": "逻辑解析",
          "slug": "逻辑解析"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "blog",
        "link": "/blog/"
      },
      {
        "text": "github",
        "link": "https://github.com/vimpare"
      }
    ],
    "sidebar": {
      "/blog/TypeScript/": [
        {
          "title": "TypeScript",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "1-基础",
              "1-基础"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/browser/": [
        {
          "title": "browser",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "Jetbrains系列产品重置试用方法",
              "Jetbrains系列产品重置试用方法"
            ],
            [
              "google扩展程序位置",
              "google扩展程序位置"
            ],
            [
              "meta",
              "meta"
            ],
            [
              "搜索框",
              "搜索框"
            ],
            [
              "渲染",
              "渲染"
            ],
            [
              "静态文件服务器",
              "静态文件服务器"
            ],
            [
              "页面刷新提示",
              "页面刷新提示"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/canvas/": [
        {
          "title": "canvas",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "粒子特效",
              "粒子特效"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/css/": [
        {
          "title": "css",
          "children": [
            [
              "",
              "前言"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/es6/": [
        {
          "title": "es6",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "ECMAScript 6 入门---阮一峰",
              "ECMAScript 6 入门---阮一峰"
            ],
            [
              "promise",
              "promise"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/jq/": [
        {
          "title": "jq",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "animate方法",
              "animate方法"
            ],
            [
              "jquery-note",
              "jquery-note"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/js/": [
        {
          "title": "js",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "utils",
              "utils"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/node/": [
        {
          "title": "node",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "glob",
              "glob"
            ],
            [
              "npm常用模块",
              "npm常用模块"
            ],
            [
              "path",
              "path"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/python/": [
        {
          "title": "python",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "generator",
              "generator"
            ],
            [
              "python函数",
              "python函数"
            ],
            [
              "python基础",
              "python基础"
            ],
            [
              "python异常",
              "python异常"
            ],
            [
              "python文件",
              "python文件"
            ],
            [
              "python类",
              "python类"
            ],
            [
              "初始",
              "初始"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/react/": [
        {
          "title": "react",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "create-react-app",
              "create-react-app"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/vue/": [
        {
          "title": "vue",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "vuex",
              "vuex"
            ],
            [
              "vue源码-1-丰富的选项合并策略",
              "vue源码-1-丰富的选项合并策略"
            ],
            [
              "vue源码-2-基础的数据代理检测",
              "vue源码-2-基础的数据代理检测"
            ],
            [
              "vue源码-3-实例挂载流程和模板编译",
              "vue源码-3-实例挂载流程和模板编译"
            ],
            [
              "vue源码-4-完整渲染流程",
              "vue源码-4-完整渲染流程"
            ],
            [
              "vue源码-5-组件基础",
              "vue源码-5-组件基础"
            ],
            [
              "vue源码-7-响应式系统构建",
              "vue源码-7-响应式系统构建"
            ],
            [
              "函数式组件",
              "函数式组件"
            ],
            [
              "插槽",
              "插槽"
            ],
            [
              "组件",
              "组件"
            ],
            [
              "过滤器",
              "过滤器"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/webpack/": [
        {
          "title": "webpack",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "1-起步",
              "1-起步"
            ],
            [
              "2-核心概念",
              "2-核心概念"
            ],
            [
              "3-管理输出",
              "3-管理输出"
            ],
            [
              "baseConfig",
              "baseConfig"
            ],
            [
              "dev-serverJS",
              "dev-serverJS"
            ],
            [
              "loader",
              "loader"
            ],
            [
              "npm scripts 使用指南",
              "npm scripts 使用指南"
            ],
            [
              "npm-concurrently",
              "npm-concurrently"
            ],
            [
              "vue-cli脚手架build目录中的dev-server.js配置文件",
              "vue-cli脚手架build目录中的dev-server.js配置文件"
            ],
            [
              "webpack-command line interface",
              "webpack-command line interface"
            ],
            [
              "webpack-modules",
              "webpack-modules"
            ],
            [
              "webpack-配置",
              "webpack-配置"
            ],
            [
              "开发",
              "开发"
            ],
            [
              "插件plugins",
              "插件plugins"
            ],
            [
              "模块热更新",
              "模块热更新"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/blog/小程序/": [
        {
          "title": "小程序",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "IntersectionObserver",
              "IntersectionObserver"
            ],
            [
              "WxValidate - 表单验证",
              "WxValidate - 表单验证"
            ],
            [
              "wxs及左滑删除",
              "wxs及左滑删除"
            ],
            [
              "小程序webview",
              "小程序webview"
            ],
            [
              "小程序原理",
              "小程序原理"
            ],
            [
              "小程序踩坑",
              "小程序踩坑"
            ],
            [
              "左滑删除2",
              "左滑删除2"
            ],
            [
              "微信小程序 - 使用npm",
              "微信小程序 - 使用npm"
            ],
            [
              "微信小程序与H5的区别",
              "微信小程序与H5的区别"
            ],
            [
              "数据请求",
              "数据请求"
            ],
            [
              "新增页面间通信接口",
              "新增页面间通信接口"
            ],
            [
              "生命周期",
              "生命周期"
            ],
            [
              "相关文件类型",
              "相关文件类型"
            ],
            [
              "组件间关系",
              "组件间关系"
            ],
            [
              "自定义组件",
              "自定义组件"
            ],
            [
              "页面事件处理函数",
              "页面事件处理函数"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/book-study/JavaScript设计模式与开发实践/": [
        {
          "title": "JavaScript设计模式与开发实践",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "16th 状态模式",
              "16th 状态模式"
            ],
            [
              "1th",
              "1th"
            ],
            [
              "20th开放-封闭原则",
              "20th开放-封闭原则"
            ],
            [
              "22th代码重构",
              "22th代码重构"
            ],
            [
              "2th",
              "2th"
            ],
            [
              "3th闭包和高阶函数",
              "3th闭包和高阶函数"
            ],
            [
              "contents",
              "contents"
            ],
            [
              "代理模式 命令模式",
              "代理模式 命令模式"
            ],
            [
              "单例模式 策略模式",
              "单例模式 策略模式"
            ],
            [
              "模板方法模式",
              "模板方法模式"
            ],
            [
              "组合模式",
              "组合模式"
            ],
            [
              "职责链模式",
              "职责链模式"
            ],
            [
              "订阅发布模式 迭代器模式",
              "订阅发布模式 迭代器模式"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/book-study/你不知道的JavaScript/": [
        {
          "title": "你不知道的JavaScript",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "中卷-第五章-语法",
              "中卷-第五章-语法"
            ],
            [
              "行为委托",
              "行为委托"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/book-study/图解http/": [
        {
          "title": "图解http",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "1th",
              "1th"
            ],
            [
              "2th",
              "2th"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ],
      "/book-study/红宝书/": [
        {
          "title": "红宝书",
          "children": [
            [
              "",
              "前言"
            ],
            [
              "10th",
              "10th"
            ],
            [
              "13th",
              "13th"
            ],
            [
              "20th-json",
              "20th-json"
            ],
            [
              "22th",
              "22th"
            ],
            [
              "23th",
              "23th"
            ],
            [
              "24th",
              "24th"
            ],
            [
              "25th",
              "25th"
            ],
            [
              "4th",
              "4th"
            ],
            [
              "8th",
              "8th"
            ],
            [
              "strictMode",
              "strictMode"
            ]
          ],
          "collapsable": false,
          "sidebarDepth": 2
        }
      ]
    }
  }
}